### ISSUE TITLE
Functionality to stop a color/dim transition

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#18]
It must be possible to start and stop a color transition (e.g. fade from the current color to red). We may decide that doing this with a service call is good enough, but it is not intuitive at all:

![grafik](https://user-images.githubusercontent.com/17641229/236830519-9b62239b-9b10-49fc-8c39-912d70361b2d.png)

**Comment by marcelveldt** [comment]
In all my time with Home Assistant I have never heard the desire to be able to stop a transition (other than sending a new command) so I do not think we should create a whole new feature for this and just take our chances with another service call. 

What we could do is create a few button entities ?

**Comment by AlCalzone** [comment]
In the expert UI:

- [ ] For each supported color component of a device, add buttons to start and stop up and down transitions of that color component. Use [`startLevelChange`](https://zwave-js.github.io/node-zwave-js/#/api/CCs/ColorSwitch?id=startlevelchange) and `stopLevelChange` API via the `zwave_js.invoke_cc_api` service.

**Comment by MartinHjelmare** [comment]
Can the expert UI use the existing service call for this?

**Comment by AlCalzone** [comment]
Yeah, or call the API directly. Not sure which is simpler to implement.

**Comment by MartinHjelmare** [comment]
Which API?

**Comment by MartinHjelmare** [comment]
The zwave-js-server client isn't exposed directly to the frontend so we need to use either a service action or a websocket command.

**Comment by AlCalzone** [comment]
I see. The above service call is probably the best way to access 99% of the advanced functionality then.

**Comment by MindFreeze** [comment]
Isn't this already added to the Expert UI?

![grafik](https://github.com/user-attachments/assets/74875b37-0d37-47b9-84aa-184d4c2c177f)

**Comment by AlCalzone** [comment]
That's Multilevel Switch (Light/Dimmer). The same needs to exist for colors, one per supported color channel. Why ever someone would want that.

**Comment by AlCalzone** [comment]
This works, but the sub-headlines say "color component 2", "color component 3" etc.
They should say "Red", "Green", "Blue", etc.:
![grafik](https://github.com/user-attachments/assets/899bb78d-5632-4567-a18b-a5b7c8aa5440)

**Comment by AlCalzone** [comment]
Confirmed
