### ISSUE TITLE
Add support for a non-dimmable color light

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#19]
[Transferred issue from AlCalzone](https://github.com/home-assistant/core/issues/92794)

As I'm going through the certification tests, I got stuck on the same issue that was reported in https://github.com/home-assistant/core/issues/80445 previously.
A test device in the certification test suite uses Binary Switch CC + Color Switch CC, so On/Off + tunable color. In this case, the end user is not able to change the color, as there is only an On/Off toggle.

**Comment by marcelveldt** [comment]
Kamino cloned this issue to [zwave-js/certification-backlog](https://github.com/zwave-js/certification-backlog/issues/22)

**Comment by marcelveldt** [comment]
We're missing a discovery schema for this light as it is on/off only (no dimming) but with color support

**Comment by AlCalzone** [comment]
It looks like this combination is not supported by the light platform, so we'll have to fake it with a dimmable light:
![grafik](https://github.com/user-attachments/assets/ebb03a08-a833-49d9-82b1-0b59993fc979)

**Comment by AlCalzone** [comment]
https://github.com/home-assistant/core/pull/122639 adds support for this. In this combination it does actually make sense to preserve the brightness slider in HA, as it allows mixing the color values with the brightness to achieve a lower light output.

**Comment by MartinHjelmare** [comment]
We've temporarily reverted the PR that fixed this issue.
