### ISSUE TITLE
Visualize Central Scenes

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#20]
Specifically this requirement:

> CL:005B.01.41.01.1 The controlling node MUST have a UI allowing the end user to see how many Scenes ID (or buttons)
and key attributes are supported by a node.

However the scenes are only "visible" to the end user once triggered:
![grafik](https://user-images.githubusercontent.com/17641229/236827753-f12b2654-1076-4166-980c-c5ee81207169.png)
... but not before that has happened.

### Diagnostics information

[zwave_js-f0926e113c178046d0d249fcdc42964a-Node 51-fc16e3b6c7d5b4fc655796a78d0657cd.json.txt](https://github.com/home-assistant/core/files/11421205/zwave_js-f0926e113c178046d0d249fcdc42964a-Node.51-fc16e3b6c7d5b4fc655796a78d0657cd.json.txt)

**Comment by marcelveldt** [comment]
A very clear candidate for the "events entity"

**Comment by AlCalzone** [comment]
Verified
