### ISSUE TITLE
Color Switch CC: Improve inspecting the current state

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#22]
A recommendation (not requirement) is this one:
> A controlling node SHOULD have a UI allowing the end user to see the following properties:
• Last known configured color or color components values

While there is a way to see the current color...
![grafik](https://user-images.githubusercontent.com/17641229/236831762-cbb2d646-950f-478e-8d01-2f381c3c0bea.png)
...I don't see a way to know **which** color that is. Would it be useful to be able to show the HEX or RGB values for that color?

This is obvious in the case of "red", but not in this case:
> Is the current level of color component 'Blue' (ID = 4) set to 130 in the DUT's UI according to Requirement Number CL:0033.01.42.01.1?

Light off: 
![grafik](https://user-images.githubusercontent.com/17641229/236832305-6d499269-2652-4d27-a173-2ddcf932a914.png)

Light on:
![grafik](https://user-images.githubusercontent.com/17641229/236832403-86da9edc-a79c-45bf-aee3-eba9433e1dd4.png)

**Comment by AlCalzone** [comment]
There is a button now to access the OS standard color picker which exposes this information.
