### ISSUE TITLE
Z-Wave JS: Notification variables are disabled by default, certification expects received notifications to be shown

### ISSUE THREAD

**Issue by raman325** [zwave-js/backlog#24]
from https://github.com/home-assistant/core/issues/94539

### The problem

Certification require:
>  A controlling node MUST have a UI allowing the end user to see the received Notification Reports (Notification Type and event/state) regarding to Requirement Number CL:0071.01.41.01.1

This works for some notifications (I assume the ones that can be auto-detected during the interview), but dynamically created ones (Notification CC v2) are hidden and disabled initially:
![Screenshot 2023-06-13 153645](https://github.com/home-assistant/core/assets/17641229/ac1013b6-496f-4b03-b72f-faf83f43475a)

When the certification tests ask questions like this...
> Does the DUT display a 'SystemHardwareFailure (0x01)' event for the notification type 'System'?

...we'll have to expect that the testers will answer **NO** unless we explicitly explain in the documentation for testers that they:
- have to show hidden entities
- have to enable them after receiving the notification for the first time
- have to wait 30s for the actual status to be shown

I'm not sure though if this will be accepted.

### What version of Home Assistant Core has the issue?

core-2023.7.0.dev20230613

**Comment by marcelveldt** [comment]
We now have the concept of diagnostic entities so we should no longer disable any entities by default at all but just mark them as diagnostic, except if its duplicated functionality (or left for legacy reasons).

Issue 2 is that the device page does not refresh whenever a new device entity is added, we should discuss that with the frontend team.

**Comment by MartinHjelmare** [comment]
We should only use the diagnostic category if it actually is a diagnostic data. Ie make sure to keep the semantics of this category. Eg measurements of the environment outside the device are typically not diagnostic while measurements of the device internals are diagnostic. Eg. compare temperature measurement vs battery level measurement. The specific of different devices vary of course.

For this case we should review what the different notifications actually measure to know how to categorize them.

**Comment by marcelveldt** [comment]
Yeah, agreed Martin, I was expecting all these values to be diagnostic only but if they are other, we should categorize them correctly. Point is that we should no longer disable them by default just to get them out of the UI, we have better ways of doing that now in 2023. Disabled entities are just confusing and we should only disable an entity if its either duplicated or legacy.

**Comment by raman325** [comment]
The other reason to disable by default is if we expect most users not to use them to avoid littering the state machine. Or is that less of a concern now with all of the work Nick has been doing on performance?

**Comment by marcelveldt** [comment]
Less of a concern unless these are some special attributes updating multiple times per minute or something ? (I dont think so)

**Comment by AlCalzone** [comment]
Another example:


![Image](https://github.com/zwave-js/certification-backlog/assets/17641229/27f5a52b-5580-4da8-8603-6ec5f8cf95e1)


The one at the bottom stays unavailable, cannot be enabled, but this is the one Z-Wave JS received a notification for.
> Does the DUT display a 'OverheatDetected (0x02)' event for the notification type 'HeatAlarm'?

**Comment by MartinHjelmare** [comment]
TODO

- [ ] Review category assigned to all entites and update if needed according to our [dev docs](https://developers.home-assistant.io/docs/core/entity#registry-properties) and rules.
- [ ] Review all entites that are disabled by default (entity_registry_enabled_default=False) and see if they have a category set so that they can be enabled by default.
- [ ] List remaining cases that don't have a category and that are currently disabled by default.

**Comment by AlCalzone** [comment]
@AlCalzone go through certification test again to see which ones don't show up by default

**Comment by AlCalzone** [comment]
Here's an example:
```
13:42:54.524 -----------------------------------------------------------------------
13:42:55.066 Done SendDataEx: Data=71 05 00 00 00 FF C0 DE 00 00; CompleteOk (Tr=1 RSc=0x03 RSp=0x03 TPw=0 Rs0=-41)        Basic COM5
13:42:55.066 -----------------------------------------------------------------------
             Does the DUT display the event ' (0xDE)' for the notification type 'Unknown (0xC0)'?
```

[zwave_js-01J2ZVFHVQG8V8J9D9360S4VCQ-Node 3-84996fc53d752344604180c9c528807c.json](https://github.com/user-attachments/files/16869684/zwave_js-01J2ZVFHVQG8V8J9D9360S4VCQ-Node.3-84996fc53d752344604180c9c528807c.json)

This value shows up during the test with a `value added` notification:
```
        "3-113-0-UNKNOWN_0xc0": {
          "commandClassName": "Notification",
          "commandClass": 113,
          "property": "UNKNOWN_0xc0",
          "endpoint": 0,
          "metadata": {
            "type": "number",
            "readable": true,
            "writeable": false,
            "label": "Unknown notification (0xc0)",
            "ccSpecific": {
              "notificationType": 192
            },
            "min": 0,
            "max": 255,
            "stateful": true,
            "secret": false
          },
          "propertyName": "UNKNOWN_0xc0",
          "value": 222
        }
```

HA shows it under sensors, but hidden: 
![grafik](https://github.com/user-attachments/assets/23c38fb5-8bb7-4462-98ae-f3ddb4c3ac18)


---

Here's another example:
```
13:46:40.464 -----------------------------------------------------------------------
13:46:41.004 Done SendDataEx: Data=71 05 00 00 00 FF 04 77 00; CompleteOk (Tr=1 RSc=0x03 RSp=0x03 TPw=0 Rs0=-38)           Basic COM5
13:46:41.005 -----------------------------------------------------------------------
             Does the DUT display the event '119 (0x77)' for the notification type 'HeatAlarm (0x04)'?
```

[zwave_js-01J2ZVFHVQG8V8J9D9360S4VCQ-Node 4-7fa2b69c5feb5dc355cd9f136f0a9406.json](https://github.com/user-attachments/files/16869729/zwave_js-01J2ZVFHVQG8V8J9D9360S4VCQ-Node.4-7fa2b69c5feb5dc355cd9f136f0a9406.json)

Like in the previous example this value shows up during the test with a `value added` notification:
```
        "4-113-0-Heat Alarm-unknown": {
          "commandClassName": "Notification",
          "commandClass": 113,
          "property": "Heat Alarm",
          "propertyKey": "unknown",
          "endpoint": 0,
          "metadata": {
            "type": "number",
            "readable": true,
            "writeable": false,
            "label": "Heat Alarm: Unknown value",
            "ccSpecific": {
              "notificationType": 4
            },
            "min": 0,
            "max": 255,
            "stateful": true,
            "secret": false
          },
          "propertyName": "Heat Alarm",
          "propertyKeyName": "unknown",
          "value": 119
        }
```

HA shows it under sensors, but hidden: 
![grafik](https://github.com/user-attachments/assets/9ba6d84e-e92a-4737-95ab-742ba8b89957)

---

One more:
```
13:49:25.324 -----------------------------------------------------------------------
13:49:25.866 Done SendDataEx: Data=71 05 00 00 00 FF C0 DE 00; CompleteOk (Tr=1 RSc=0x03 RSp=0x03 TPw=0 Rs0=-41)           Basic COM5
13:49:25.866 -----------------------------------------------------------------------
             Does the DUT display the event ' (0xDE)' for the notification type 'Unknown (0xC0)'?
```

[zwave_js-01J2ZVFHVQG8V8J9D9360S4VCQ-Node 4-7fa2b69c5feb5dc355cd9f136f0a9406(1).json](https://github.com/user-attachments/files/16869768/zwave_js-01J2ZVFHVQG8V8J9D9360S4VCQ-Node.4-7fa2b69c5feb5dc355cd9f136f0a9406.1.json)

Like before, the sensor is hidden by default.

**Comment by joostlek** [comment]
https://github.com/home-assistant/core/pull/125326
