### ISSUE TITLE
Treat Basic CC `currentValue` without `targetValue` as a numeric (?) sensor instead of a light

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/backlog#28]
The recent changes to Basic CC exposed an issue where devices that "support" Basic CC, but cannot actually be controlled, appear as a light entity. The next version of `node-zwave-js` only exposes `currentValue` in this case.

This needs a change in the discovery scheme, so that `currentValue` without `targetValue` is considered a sensor and not a light/actor.

**Comment by raman325** [comment]
got a device dump I can use?

**Comment by raman325** [comment]
also is this going to require a reinterview?

**Comment by AlCalzone** [comment]
Do you have an Aeotec Multisensor 6 or something similar? That should exhibit the behavior.
I think it might require a re-interview too because the Basic CC support information needs to be set correctly.

**Comment by raman325** [comment]
> Do you have an Aeotec Multisensor 6 or something similar? That should exhibit the behavior. I think it might require a re-interview too because the Basic CC support information needs to be set correctly.

I don't but it's fine, I will take the existing Aeotec Multisensor 6 dump and modify it for this purpose

**Comment by marcelveldt** [comment]
We had a little chat about this and came to a few conclusions;

- [x] - The driver should hide Basic CC when it knows for certain there's a better alternative
- [ ] - We should create a sensor from Basic CC without targetValue
- [ ] - We should create switch + number entity for Basic CC with targetValue
- [ ] - We should not abuse light platform for Basic CC
- [x] - Nice to have would be that the device database can include info when to hide Basic CC

**Comment by AlCalzone** [comment]
Regarding the 1st point:
- https://github.com/zwave-js/node-zwave-js/pull/6760 fixes an issue where mapped and hidden CCs could still contribute values that show up in UIs
- https://github.com/zwave-js/node-zwave-js/pull/6773 adds the capability to map Basic CC to Binary Sensor CC for devices where this cannot be automatically determined. We'll have to incrementally identify devices that need this and update their config files.

...so I consider that done - the rest is on the HA side.
