### ISSUE TITLE
Allow GET/SET config value of a custom configuration parameter

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/backlog#31]
Allow the user to GET/SET a custom configuration value for a device.
The device configuration panel needs to be expanded, as well as the websocket.

![Image](https://github.com/zwave-js/certification-backlog/assets/6389780/04832ac3-d5d5-4aed-b304-1c8f07109222)

**Comment by AlCalzone** [comment]
Related to this, I tried to use the `set_config_parameter` service to set an unknown config parameter as part of the certification tests and got this error, which kind of defeats the purpose of this service call UI (and causes the test to fail):



![Image](https://github.com/zwave-js/certification-backlog/assets/17641229/109289a8-74af-4d45-8831-d8f4080dd34f)

**Comment by marcelveldt** [comment]
expert UI

**Comment by MindFreeze** [comment]
In order to remove the error from the service and make custom params possible we need this PR https://github.com/home-assistant-libs/zwave-js-server-python/pull/1080

**Comment by AlCalzone** [comment]
This is not working correctly. When getting a config parameter, the message sent to `zwave-js-server` has the parameter number in an `options` object, when it should be directly on the message:
![Image](https://github.com/user-attachments/assets/d72d9707-5138-4ef9-b1a6-501e58527ece)

vs.

![Image](https://github.com/user-attachments/assets/69668a52-e5dd-4ad0-bc2c-d6ed4c379a25)

**Comment by AlCalzone** [comment]
Setting a value of 0 fails frontend validation:
![grafik](https://github.com/user-attachments/assets/57ea7a3e-07d1-4986-a88d-b2f6222b031d)

And when frontend validation passes, the message also has the incorrect `options` parameter:
![grafik](https://github.com/user-attachments/assets/bb009749-9388-42d3-b8b8-72118ed649a9)

**Comment by MindFreeze** [comment]
> This is not working correctly. When getting a config parameter, the message sent to `zwave-js-server` has the parameter number in an `options` object, when it should be directly on the message: ![Image](https://private-user-images.githubusercontent.com/17641229/385286571-d72d9707-5138-4ef9-b1a6-501e58527ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjI5NjcsIm5iZiI6MTczMTQyMjY2NywicGF0aCI6Ii8xNzY0MTIyOS8zODUyODY1NzEtZDcyZDk3MDctNTEzOC00ZWY5LWIxYTYtNTAxZTU4NTI3ZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNzg5YjAzZDAxMDcyYzgwYWQ5MTIxYjU4YjFmNTk4N2IxNzU2OGI0NjViMzFkMTE4ZDJhOTIyNTI3ZDM2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ul1qUGXxVd2sGwGUf-Kg7HOKiNV4iLD-RPYpNTTpkq4)
> 
> vs.
> 
> ![Image](https://private-user-images.githubusercontent.com/17641229/385286698-69668a52-e5dd-4ad0-bc2c-d6ed4c379a25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjI5NjcsIm5iZiI6MTczMTQyMjY2NywicGF0aCI6Ii8xNzY0MTIyOS8zODUyODY2OTgtNjk2NjhhNTItZTVkZC00YWQwLWJjMmMtZDZlZDRjMzc5YTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1N2NjYzg0MWM4ZjU3MDliOGRmZjJjMmM3YTA3ZDI4MTE3NmM2OGQwOGM5NDY1YzRiNDg3YzA0MzgxY2MwNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sfOwO3UIzMPtYLjUze6Z8_V9b7LBcL55FbEMjOpdAgo)

This should be ok as it is transformed in the zwavejs-server https://github.com/zwave-js/zwave-js-server/blob/1fb161d20a6714489f8e05ad59e7cb66f18ba5cd/src/lib/common.ts#L95-L108

**Comment by AlCalzone** [comment]
The screenshot shows the actual contents of `message` (see the `options` property), which does not adhere to the `IncomingCommandNodeGetRawConfigParameterValue` interface.
The `message.parameter` in the code you linked **does not** exist, it is available under `message.options.parameter`, which **should not** exist.

**Comment by MindFreeze** [comment]
The fix has been merged into core

**Comment by AlCalzone** [comment]
This works, but it highlighted a new UI issue: https://github.com/zwave-js/certification-backlog/issues/52
