### ISSUE TITLE
Reopening the Add Device dialog should be possible

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/backlog#33]
When reopening the integration page while searching for a device, this info appears at the top:

![Image](https://github.com/zwave-js/certification-backlog/assets/17641229/7f872f38-0d7f-49ae-a6e0-ab2d15c9f0b1)

While it allows stopping the search, it does not help when including an S2 device. The PIN entry dialog does not appear. Maybe it shouldn't even be possible to interact with this page while searching for a device?

**Comment by MindFreeze** [comment]
Hah. I guess I tackled this while dealing with #35 . See https://github.com/zwave-js/certification-backlog/issues/35#issuecomment-2435214985

**Comment by MindFreeze** [comment]
Done with https://github.com/home-assistant/frontend/pull/22519
