### ISSUE TITLE
"Stop Searching" should abort S2 bootstrapping when clicked after the inclusion is complete

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/backlog#34]
This button does nothing when the inclusion has already been completed and Z-Wave JS is waiting for S2 bootstrapping to complete:

![Image](https://github.com/zwave-js/certification-backlog/assets/17641229/2e4c240d-8338-478b-a205-427bb6954c99)

It should probably call the `abort()` user callback so Z-Wave JS can abort S2 bootstrapping. Otherwise the user is stuck without being able to do anything until bootstraping times out after 4 minutes.

**Comment by MindFreeze** [comment]
@AlCalzone I have questions.
1. How can I recognize this state?
2. What is this `abort()`? I only see this but it seems to be a callback on abort, not triggering an abort https://zwave-js.github.io/node-zwave-js/#/getting-started/security-s2?id=conventional-inclusion-process

**Comment by AlCalzone** [comment]
For 1.:
The `"node found"` controller event was received, and the `"node added"` event for the same node ID was not received yet.

For 2.: `abort()` is wrong, as you correctly noticed. You need to call `controller.cancelSecureBootstrapS2(KEXFailType.BootstrappingCanceled)`.
