### ISSUE TITLE
"Add device" without function, "Remove device" does not re-enable after an inclusion/bootstrapping was completed in the background

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/backlog#35]
I started including a device, reloaded the page, then completed inclusion. The button stayed disabled:

![Image](https://github.com/zwave-js/certification-backlog/assets/17641229/a173d850-8295-46ed-9cf2-d9d8e3f5821d)

and "add device" simply did nothing. After reloading the page again, it went back to normal.

**Comment by MindFreeze** [comment]
I'm changing this page to reopen the dialogs for add/remove after a refresh, so the process can resume seamlessly

**Comment by MindFreeze** [comment]
https://github.com/home-assistant/frontend/pull/22519
