### ISSUE TITLE
Show value range of config parameter in UI

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#38]
When setting config values for a device in the frontend, the user needs to know the valid value range.
This information should already be present in the data provided to the frontend and its just a matter of showing it.

Bonus points: input validation in the frontend if the value is in range ?

**Comment by bramkragten** [comment]
> Bonus points: input validation in the frontend if the value is in range ?

This is already done, but could be improved in reporting, it now still tries to send the command instead of clearly showing the error :-)

![CleanShot 2024-09-05 at 13 49 48](https://github.com/user-attachments/assets/107c7713-3df6-4bd9-81a0-4239bf7bb206)

**Comment by bramkragten** [comment]
![CleanShot 2024-09-05 at 13 55 49](https://github.com/user-attachments/assets/f545f532-79b4-468e-bf4a-b9507fb1b9d0)

**Comment by AlCalzone** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/21892
