### ISSUE TITLE
Show default value for device config parameter

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#40]
In the frontend panel where a user can configure the device configuration parameters, we need to show the default value.
This information should also be present in the current data (just like the min/max values) but its probably not yet exposed in the websocket command. It should be present in the value metadata.

**Comment by marcelveldt** [comment]
backend PR: https://github.com/home-assistant/core/pull/125343

**Comment by wendevlin** [comment]
Frontend PR: [home-assistant/frontend#21990](https://github.com/home-assistant/frontend/pull/21990)

**Comment by AlCalzone** [comment]
@wendevlin is that the right PR? Seems to be about resetting all parameters --> https://github.com/zwave-js/certification-backlog/issues/39

**Comment by wendevlin** [comment]
> @wendevlin is that the right PR? Seems to be about resetting all parameters --> #39

I updated the title of the PR now. It does solve #39 and #40
