### ISSUE TITLE
Handle S2 inclusion via Inclusion Controller

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/backlog#45]
https://github.com/zwave-js/node-zwave-js/issues/5888 for background

The ideal course of action to solve this is [outlined here](https://github.com/zwave-js/zwave-js-ui/issues/3141#issuecomment-1607021694).

HA must then prompt the user to enter PIN and/or grant security classes when asked.

update [july 4th 2024]
Just add a listener in the zwave_js frontend panel to popup a dialog when this happens.

**Comment by MindFreeze** [comment]
So an event must be sent from the driver all the way to the HA frontend.
How far along is this? Is it supported in zwavejs, server, HA lib, HA core? I know it's not in the frontend

**Comment by AlCalzone** [comment]
The callback/event itself is already looped through, as it's the same that's used during the normal S2 inclusion flow to show the PIN entry etc.

The core addon may need to tell the server to set the callbacks on start if it doesn't already:
https://github.com/zwave-js/zwave-js-server/blob/1fb161d20a6714489f8e05ad59e7cb66f18ba5cd/src/lib/server.ts#L503

When using Z-Wave JS UI, this should already be handled correctly. Z-UI receives the events only when it is open, otherwise they are forwarded to HA.

**Comment by MindFreeze** [comment]
Looks like the event is always enabled when starting the server from the CLI so the addon must be fine https://github.com/zwave-js/zwave-js-server/blob/1fb161d20a6714489f8e05ad59e7cb66f18ba5cd/src/bin/server.ts#L186
