### ISSUE TITLE
Add controls for Door Lock CC to expert UI

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/backlog#48]
![grafik](https://user-images.githubusercontent.com/17641229/215498465-c3e6415b-4e1a-4656-84cc-b12883030711.png)

(the mentioned operation types mean **constant** `0x01` and **timed** `0x02`, V4+ adds additional ones)

---

**Tasks:**
- [ ] Move the service call functionality to the expert UI. This needs one block where:
    * User can select operation type among supported (Timed, Constant)
    * User can check/uncheck inside/outside door handles (4, amount can not be detected)
    * If operation type is timed, set the timeout min:sec
    * If supported, set the auto relock time in seconds
    * If supported, set the hold-and-release time in seconds
    * If supported, enable/disable block-to-block functionality
    * If supported, enable/disable twist assist
    * One button to apply the changes

- [ ] Afterwards, verify if this requirement is fulfilled for the door lock mode control on the device page:
> Timed Operation modes MUST NOT be selectable by the end user if the
door lock is not configured in Timed Operation

**Comment by wendevlin** [comment]
Zwave-JS reference:
https://zwave-js.github.io/node-zwave-js/#/api/CCs/DoorLock?id=door-lock-cc-methods

**Comment by AlCalzone** [comment]
The existing service call may also be a good reference.

**Comment by MindFreeze** [comment]
I guess inside/outside handles are not needed https://github.com/home-assistant/core/pull/103595#discussion_r1394120321

**Comment by AlCalzone** [comment]
We can add them if we want. If not, they **should** all be set to true in the API call
