### ISSUE TITLE
Home Assistant (probably) needs to support Identify

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#5]
https://github.com/home-assistant/core/pull/90248 added support for identifying nodes.
Apparently identifying is also a certification requirement for controllers, although I fail to see how it makes sense for us, given that we have a full-blown UI. Also I'm unclear how this identification must be done, since the specs are only referring to "nodes" and recommend that they blink an LED.
On the other hand, the certification test asks "Did the DUT blink 5 times?" 🤷‍♂️

Anyways, the next `node-zwave-js` release will add a controller event `"identify"`, which HA probably needs to capture and show some sort of identification as a result. Ideally keep in mind that something may have to blink a configurable amount of times.

**Comment by marcelveldt** [comment]
Home Assistant is a software controller. 
First conclusion is that we should just create a persistent notification on the Identify event and that will be sufficient.

**Comment by AlCalzone** [comment]
Verified
