### ISSUE TITLE
Notify user about factory reset of end devices

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#6]
The specifications mandate this:
> A controlling node receiving the Device Reset Locally Notification Command MUST indicate to the
end user that the node has been reset and left the Z-Wave network.

To accomodate, v11 of `node-zwave-js` has added a parameter that indicates **why** a node was removed:
https://zwave-js.github.io/node-zwave-js/#/api/controller?id=quotnode-removedquot

When this reason is `RemoveNodeReason.Reset`, HA must notify the user. Other reasons, like `ProxyExcluded` or `ProxyReplaced` may be interesting too, but not mandatory.

**Comment by AlCalzone** [comment]
One remaining issue: The integration must be reloaded before the device gets removed from HA. This fails this requirement:
> Has the DUT removed this node (ID = 3) from its Z-Wave nodes list? (see Requirement Number CL:005A.01.52.01.1)
