### ISSUE TITLE
Create (light) entity for Basic CC

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#7]
From core created by [AlCalzone](https://github.com/AlCalzone): home-assistant/core#92789  

### The problem

Some devices only support Basic CC, and no other actuator CC like Binary Switch, etc.
For those devices, the specs require that users can use the Basic CC to interact with the device and view the current status.

However, the Basic CC entities are hidden by default and have to be enabled manually: 
![grafik](https://user-images.githubusercontent.com/17641229/236809647-7143a595-9c2f-46e1-9702-bf0f1e9da990.png)

While this is usually fine, this shouldn't be done if Basic CC is the only way to control the device. I think HA should rely on the information by the driver and show the Basic CC values by default. The `node-zwave-js` driver already hides Basic CC from applications, unless:
* no other actuator CC is supported
* the "Basic event" value is enabled via a config file

---

Also, it is currently not possible to send an "ON" command (255). Basic CC has the same value range as Multilevel Switch CC (0-99, 255). The value slider only allows setting 0-99
![grafik](https://user-images.githubusercontent.com/17641229/236824651-7914e0fd-a407-47de-b079-bae2cbf07ef2.png)
but sending a 255 is a check in the certification test suite.

### Diagnostics information

[zwave_js-f0926e113c178046d0d249fcdc42964a-Node 48-d2b1f1f13b9c6bab2d0d79efbc1d3724.json.txt](https://github.com/home-assistant/core/files/11421115/zwave_js-f0926e113c178046d0d249fcdc42964a-Node.48-d2b1f1f13b9c6bab2d0d79efbc1d3724.json.txt)

**Comment by marcelveldt** [comment]
We should add the Basic CC to the light discovery schema and not hide it by default, as that is already done by the driver itself.

@AlCalzone is it ok that this will always be translated into a light control within the Home Assistant UI ? Or will the device type give us some clue whether this is a light or a fan (or some other device that has level control and on/off) ?

**Comment by AlCalzone** [comment]
AFAIK fans have discrete steps in HA, so it would make some of the functionality inaccessible. I think treating it as a light is fine, even if that ends up not being the actual device type.

**Comment by marcelveldt** [comment]
@AlCalzone can you create a mock device for a light from basic CC ?

**Comment by AlCalzone** [comment]
Here it is:
```js
// @ts-check
const { CommandClasses } = require("@zwave-js/core");
require("@zwave-js/testing");

/** @type {import("zwave-js/Testing").MockServerOptions["config"]} */
module.exports.default = {
	nodes: [
		{
			id: 2,
			capabilities: {
				commandClasses: [CommandClasses.Version, CommandClasses.Basic],
			},
		},
	],
};
```

Needs latest `node-zwave-js` master for the correct behavior.

**Comment by raman325** [comment]
> The `node-zwave-js` driver already hides Basic CC from applications, unless:
> - no other actuator CC is supported
> - the "Basic event" value is enabled via a config file

So do we create the light entity in all of these scenarios? or just the first one?

**Comment by AlCalzone** [comment]
IMO: Create the light entity when Z-Wave JS exposes `currentValue` and `targetValue`

**Comment by marcelveldt** [comment]
There could be a potential case where a device is actually a fan but we now think this is a real edgecase so its fine to treat the basic CC as light. If we ever get any reports about this we may want to think this over like providing a "hint" from the driver to HA in the basic CC to determine which entity platform to use.

**Comment by AlCalzone** [comment]
Tested and verified
