### ISSUE TITLE
Refresh a notification type through the UI

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#9]
From core created by [AlCalzone](https://github.com/AlCalzone): home-assistant/core#94543  

### The problem

> 16:20:31.009 Please trigger a Alarm Get using the DUT's UI!
16:20:31.009 
16:20:31.009 *******************************************************************
16:20:31.009    Timeout for Test sequence is 5 min, waiting for following events:
16:20:31.009     * NOTIFICATION_GET (ALARM_GET) for Notification Type 0x09
16:20:31.010 *******************************************************************

The only way to do this currently is this service call, which requires looking up Z-Wave JS source code to know what to put there:

![grafik](https://github.com/home-assistant/core/assets/17641229/fb506789-3ce4-41a4-b0aa-e6bd1c89ca73)

**Comment by marcelveldt** [comment]
As this is considered a very advanced scenario, it will most probably suffice to just have another service available to query/refresh a particular notification type ?

**Comment by AlCalzone** [comment]
Works
